### ISSUE TITLE
Character layer specialization init

### ISSUE THREAD

**Issue by L1nked2** [L1nked2/LostarkDPM#15]
How we import specialization(특화) for each class?
Candidates
1. Specialization gives maximum 4 attributes, so add on character_layer -> need class_name and each function for class
2. Just save specialization value and apply on identity -> do it on later

**Comment by hyung1721** [comment]
Me, 2 is better
- though specialization gives at most 4 attributes, the details of each attribute may be different class by class, except awakening damage increment. Some details are strongly related to identity of class.
- I think character_layer should contain info about only combat stat & damage, etc., not class related things, which is more natural. What about processing specialization in identity layer by implementing it in `/src/classes/<class_name>.py`?

**Comment by L1nked2** [comment]
1. awakening_damage_mutiplier is saved to character_layer
2. specialization value is saved in character_layer and to be handled in identity layer
