### ISSUE TITLE
기상술사 관련

### ISSUE THREAD

**Issue by UnionHHS** [L1nked2/LostarkDPM#38]
인벤에서 보구왔슴다! (인벤 쪽지를 통해 문의 남기려했는데 4렙따리 흰딱이라.. 여따 남겨드림다)

여우비 활성화 결과데이터가 0으로 떠서 뒤적거리다가 데이터가 다 0으로 되어있는걸 봐버려서
유툽 영상 따라서 계산한 데이터 따라서 남겨드림다...!

{
      "name": "여우비 활성화",
      "level": 12,
      "tripod": "000",
      "default_damage": 632,
      "base_damage_multiplier": 3.9,
      "cooldown": 999999,
      "skill_type": "Common",
      "identity_type": "Common",
      "common_delay": 0.75,
      "type_specific_delay": 0.0,
      "jewel_cooldown_level": 0,
      "jewel_damage_level": 10,
      "head_attack": false,
      "back_attack": false,
      "key_strokes" : 0,
      "rune": "None"
    }

**Comment by UnionHHS** [comment]
+ 해당 데이터는 특화 60기준임다
60 = 기상스킬 피해량 4.29% 증가

**Comment by L1nked2** [comment]
/src/classes/aeromancer.py 참조 바랍니다.
여우비의 경우 aeromancer.py 내부 dictionary로 별도 관리합니다. 지속 딜링 형태의 버프를 활성화 하는 방식이기 때문입니다.
결과창에서는 sunshower_damage로 표시되며, aeromancer.py에 기재된 내용은 아래와 같습니다.

```
# 여우비 데미지 버프(10멸 기준)
  'Sunshower_Damage': {
    'name': 'sunshower_damage',
    'buff_type': 'damage',
    'effect': None,
    'base_damage': 632 * 1.4,
    'coefficient': 3.918 * 1.4,
    'damage_interval': 1,
    'duration': DEFAULT_SUNSHOWER_TIME_LIMIT,
    'priority': 7,
  },
```

별개로 특화로 인한 딜 증가는 여우비 활성화하는 부분인 activate_sunshower에서 처리합니다.
감사합니다.

**Comment by UnionHHS** [comment]
아하 제가 그 결과값볼때 ('sunshower_damage', 2933213), ('여우비 활성화', 0) 이렇게 적혀있어서 계산 안되는줄 알고있었습니다!

감사합니다!
