### ISSUE TITLE
Nightmare2+Salvattion4 wrong buff

### ISSUE THREAD

**Issue by Villentretheimert** [L1nked2/LostarkDPM#51]
In salvation buff, there's added value of 0,14, when for slavation 4 set, buff is 1,4% per stack, so 0,28. Issue is in all lvls of set
![image](https://github.com/L1nked2/LostarkDPM/assets/65677417/88c19be3-873e-4093-a10f-a344c29d0698)

**Comment by L1nked2** [comment]
Thank you for your report!
