### ISSUE TITLE
5월 패치 리퍼 딜 에러

### ISSUE THREAD

**Issue by tmchojo** [L1nked2/LostarkDPM#59]
![err](https://github.com/L1nked2/LostarkDPM/assets/16629196/fa8351e0-e4ec-44e9-b1eb-82483f0afe89)
2305패치로 달소는 4.3%, 갈증은 2.5%딜증이 있었는데,
링크드님의 표에서는 달소 7.5%, 갈증 6.4%딜증으로 나타나는 에러가 있습니다.

**Comment by L1nked2** [comment]
중간 커밋 과정을 살펴본 결과 각인 변경, 특화 계수 변경으로 인한 기존 계수 수정 영향으로 보입니다.

**Comment by tmchojo** [comment]
그럼 잘못된 부분을 찾아서 수정해야되지 않을까요?
딜이 3-4프로나 잘못 표시되고 있는건데요

**Comment by L1nked2** [comment]
모든 변경사항은 다음과 같습니다
1. 방깎 시너지의 계산을 보다 정확하게 수식 수정
2. 쉐도우 스톰의 트포 채용이 변경
3. 밸런스 패치로 인한 계수 상승
4. 특화 계수를 보다 정확하게 수정

상기 변경 사항중 1번과 2번으로 인해 예상되었던 값과 달라졌지만, 더 정확한 값이라고 보여집니다.
감사합니다.
